[package]
name = "raytracer"
version = "0.1.0"
authors = ["Joseph Thomas <josephdt12@gmail.com>"]
edition = "2018"

[lib]
name = "raytracer"

[[bin]]
name = "raytracer"

[dependencies]
rand = "0.7.3"
